databases:
  - name: flaskshop-db
    databaseName: flaskshop
    user: flaskshop
    plan: free

services:
  - type: web
    name: flaskshop
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --workers 4 --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flaskshop-db
          property: connectionString
